# Generated by Django 5.2.8 on 2025-11-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attendants', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Animatronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('animal', models.CharField(choices=[('BE', 'Bear'), ('CH', 'Chicken'), ('BU', 'Bunny'), ('FO', 'Fox')], max_length=2, verbose_name='Animal type')),
                ('build_date', models.DateField(verbose_name='Build date')),
                ('decommissioned', models.BooleanField(default=False, verbose_name='Decommissioned')),
                ('parties', models.ManyToManyField(blank=True, to='freddyapp.party', verbose_name='Parties')),
            ],
        ),
    ]
